Add cli-progress to the repack cli
callstack/repack pull request #377
Opened 2023-06-13 16:34 UTC by emel95

I've been using Repack for quite a while and although the functionalities of this project impressed me, I wasn't happy with the way progress of bundling process was shown in the terminal. So, I rolled up my sleeves and tried to make it neater and as informative as before for the developers who want to utilize this package.

The package that I used for this matter is "cli-progress" and changed the "consoleReporters.js" file. Feel free to change the way progress is shown on the Terminal by changing the presets bundled with the mentioned package and let me know if any changes from my side was required.

2023-06-15 11:52 UTC, szymonrybczak commented on packages/repack/package.json
> +    "cli-progress": "^3.12.0",
Please install `@types/cli-progress` in `devDependencies` because the library code is not compiling.

2023-06-15 11:53 UTC, szymonrybczak commented on packages/repack/src/logging/reporters/ConsoleReporter.ts
> +  constructor(private config: ConsoleReporterConfig) { }
Why did you make this change? Make sure to correctly setup eslint and prettier.

2023-06-15 11:54 UTC, szymonrybczak commented on packages/repack/src/logging/reporters/ConsoleReporter.ts
> +        `${IS_SYMBOL_SUPPORTED ? SYMBOLS[log.type] : FALLBACK_SYMBOLS[log.type]
Same as above. Please make sure that you have correctly setup litner.

2023-06-15 12:09 UTC, szymonrybczak commented on packages/repack/src/logging/reporters/ConsoleReporter.ts
> +    format: 'Compiling {platform}: ' + '|{bar}|' + ' %{percentage}' + ' ',
Make sure to handle the initial state. Right now when the progress is 0% there's label with the placeholder "Compiling **{platform}**". Please do not show this placeholder.
![CleanShot 2023-06-15 at 14 09 09@2x](https://github.com/callstack/repack/assets/63900941/08605da4-7953-47a9-9c84-2ac0ffe57ec8)

2023-06-15 12:16 UTC, szymonrybczak commented
💡 Do we want to have the progress bar in the same format as other logs? Because right know this progress bar is without any timestamp. cc. @RafikiTiki 
<img width="765" alt="CleanShot 2023-06-15 at 14 16 06@2x" src="https://github.com/callstack/repack/assets/63900941/d85b5fde-ecd2-4dd8-8040-de39305368f6">

2023-08-08 11:36 UTC, szymonrybczak commented
@emel95 any updates? 🙏

2023-08-15 16:42 UTC, emel95 commented
@szymonrybczak  
hi
I have fixed the issues you mentioned. I hope they are okay now. If there are any further problems, please let me know so that I can address them. Thank you.

2023-08-16 10:51 UTC, jbroma commented
Hi @emel95,

First of all, thanks for making an effort to contribute to Re.Pack!

I've reviewed the PR and found the following issues:
- to support bundling for both platforms at the same time, you probably want to use multi-bar instead of a single-bar, otherwise it will keep replacing itself and the output gets messy
- every log now has additional `\n` and there are lots of unnecessary empty lines
- we probably don't want to display the bar when there is no compilation taking place at the start and only start displaying it when the actual compilation is underway 
- the bar get's redrawn and the old one stays in place, would be nice to somehow fix this behaviour and remove the old bar before drawing the new one, and maybe keep it always at the bottom of the output from Re.Pack?

This is how it looked in my terminal:
<img width="1159" alt="image" src="https://github.com/callstack/repack/assets/20626315/206ad6bb-6468-45e1-875f-6c7c57a4fb63">

2023-08-16 10:52 UTC, jbroma requested changes
Hi @emel95,

First of all, thanks for making an effort to contribute to Re.Pack!

I've reviewed the PR and found the following issues:
- to support bundling for both platforms at the same time, you probably want to use multi-bar instead of a single-bar, otherwise it will keep replacing itself and the output gets messy
- every log now has additional `\n` and there are lots of unnecessary empty lines
- we probably don't want to display the bar when there is no compilation taking place at the start and only start displaying it when the actual compilation is underway 
- the bar get's redrawn and the old one stays in place, would be nice to somehow fix this behaviour and remove the old bar before drawing the new one, and maybe keep it always at the bottom of the output from Re.Pack?

This is how it looked in my terminal:
<img width="1159" alt="image" src="https://github.com/callstack/repack/assets/20626315/206ad6bb-6468-45e1-875f-6c7c57a4fb63">

2023-08-20 16:03 UTC, emel95 commented
hi @jbroma
Thank you for your complete explanation, I changed the things you said, please check again

2023-09-26 17:19 UTC, emel95 commented
hi @jbroma
any updates?🙏

2023-09-27 10:34 UTC, jbroma commented
Hi @emel95,

some of the issues I mentioned above are still not resolved, try bundling 2 apps at once and see how the progress bars just keep overwriting themselves. 

P.S. I realise this not a trivial issue to fix

2023-12-10 13:41 UTC, emel95 commented
hi
I will try to start these mentioned items in a few days and fix them as soon as possible

2024-03-21 00:12 UTC, closed without merging