fix: prevent to load script again
callstack/repack pull request #756
Opened 2024-09-21 11:17 UTC by hosseinmd

https://github.com/callstack/repack/issues/749
### Summary
In this PR, I prevented `loadScript` to load scripts is loaded before

### Test plan
This is happening in remote federation with huge size of script and too many modules

2024-09-29 11:04 UTC, jbroma requested changes
Hey @hosseinmd, sorry for the late reply but I was unavailable most of the week.

The concept introduced in this PR looks great, we definitely want this in the next major (5.0) release!

Can you please add some tests for this scenarios? We need to document this behaviour as well as we can

I've also noticed that we're using the same variable 
`sriptsPromises` for both prefetching and loading - while in theoery these should not overlap, I would go with creating a separate variables to avoid potential collision in rare edge cases. 

We also need to address housekeeping of the promises that have already been fulfilled - we should remove the entires from `scriptsPromises` that are not relevant anymore.

Last thing that comes to my mind: perhaps we could return a promise in `prefetchScript` and `loadScript` instead of executing loadProcess again after awaiting the previous promise?

2024-09-30 09:18 UTC, hosseinmd commented
> Can you please add some tests for this scenarios? We need to document this behaviour as well as we can

Yes, I will do it

2024-09-30 09:23 UTC, hosseinmd commented
> I've also noticed that we're using the same variable
> `sriptsPromises` for both prefetching and loading - while in theoery these should not overlap, I would go with creating a separate variables to avoid potential collision in rare edge cases.

`loadScript` and `prefetchScript` are using same `resolveScript`. If we separate those, the same bug https://github.com/callstack/repack/issues/749 possible to be happening.

2024-09-30 09:25 UTC, hosseinmd commented
> We also need to address housekeeping of the promises that have already been fulfilled - we should remove the entires from `scriptsPromises` that are not relevant anymore.

Ok, I will do it.

2024-09-30 12:12 UTC, hosseinmd commented
> > I've also noticed that we're using the same variable
> > `sriptsPromises` for both prefetching and loading - while in theoery these should not overlap, I would go with creating a separate variables to avoid potential collision in rare edge cases.
> 
> `loadScript` and `prefetchScript` are using same `resolveScript`. If we separate those, the same bug #749 possible to be happening.

i added a test for that. https://github.com/callstack/repack/pull/756/commits/969d6d8819498ffe95ba797c414ffabcb4810358

2024-09-30 13:40 UTC, hosseinmd commented
> > I've also noticed that we're using the same variable
> > `sriptsPromises` for both prefetching and loading - while in theoery these should not overlap, I would go with creating a separate variables to avoid potential collision in rare edge cases.
> 
> `loadScript` and `prefetchScript` are using same `resolveScript`. If we separate those, the same bug #749 possible to be happening.

In this https://github.com/callstack/repack/pull/756/commits/ee3a58c5f3f2d9d2a9ae44c47d3d0fe4b72fbdb6 commit loadScript will excute script if promise is for prefetch

2024-09-30 14:01 UTC, jbroma commented
@hosseinmd can you merge newest main and resolve the conflicts? Then I will proceed with another review, thanks!

2024-09-30 17:02 UTC, hosseinmd commented
Done

2024-09-30 18:32 UTC, jbroma commented
> Done

Nice job! I'll try to review it later today

2024-10-02 10:29 UTC, jbroma requested changes
lets clean this up a little bit, other than these few things, nice job!

2024-10-02 10:29 UTC, jbroma commented on packages/repack/src/modules/ScriptManager/__tests__/Federated.test.ts
can we move this to a a file with ScriptManager tests? almost all of the setup feels repeated here.

2024-10-02 10:29 UTC, jbroma commented on packages/repack/src/modules/ScriptManager/__tests__/Federated.test.ts
> +  it('should wait loadScript with same scriptId to finished ', async () => {
```suggestion
  it('should await loadScript with same scriptId to finish ', async () => {
```

2024-10-02 10:29 UTC, jbroma commented on packages/repack/src/modules/ScriptManager/ScriptManager.ts
> +  > = {};
lets move this type to a separate line

2024-10-03 18:04 UTC, hosseinmd commented
Done

2024-10-07 13:55 UTC, jbroma requested changes
all looks good, just one last thing 🙏

2024-10-07 13:55 UTC, jbroma commented on packages/repack/src/modules/ScriptManager/__tests__/ScriptManager.test.ts
> +  ),
can we only apply this mock implementation to the selected tests that we need? I think this can be achieved with `jest.spyOn`

2024-10-16 12:30 UTC, hosseinmd commented
Last commits rebased

2024-10-16 13:01 UTC, jbroma approved these changes
LGMT 🎉

2024-10-17 11:04 UTC, merged

2024-10-17 11:05 UTC, jbroma commented
Thank you for your work on this @hosseinmd, this was no easy issue to tackle! 👏 🚀